// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from "node:path";
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

const rootDir = process.cwd();

dotenv.config({ path: path.resolve(rootDir, ".env") });
dotenv.config({ path: path.resolve(rootDir, ".env.local"), override: true });

if (!process.env.DATABASE_URL) {
  dotenv.config({ path: path.resolve(rootDir, ".env.production") });
  dotenv.config({
    path: path.resolve(rootDir, ".env.production.local"),
    override: true,
  });
}

const useDirectUrl = process.env.PRISMA_USE_DIRECT_URL === "1";
const rawDatabaseUrl = useDirectUrl
  ? process.env["DATABASE_URL_DIRECT"] || process.env["DATABASE_URL"]
  : process.env["DATABASE_URL"] || process.env["DATABASE_URL_DIRECT"];

const parsedDatabaseUrl = rawDatabaseUrl ? new URL(rawDatabaseUrl) : null;
const isSupabasePooler =
  parsedDatabaseUrl !== null &&
  !useDirectUrl &&
  parsedDatabaseUrl.hostname.endsWith(".pooler.supabase.com");

if (isSupabasePooler) {
  const url = parsedDatabaseUrl as URL;
  if (!url.searchParams.has("pgbouncer")) {
    url.searchParams.set("pgbouncer", "true");
  }
  if (!url.searchParams.has("statement_cache_size")) {
    url.searchParams.set("statement_cache_size", "0");
  }
  if (!url.searchParams.has("connect_timeout")) {
    url.searchParams.set("connect_timeout", "15");
  }
}

const databaseUrl = parsedDatabaseUrl?.toString() || rawDatabaseUrl;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
